services:
  db-purchasing:
    image: mysql:8
    container_name: purchasing-db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: purchasing
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    networks:
      - app-network

  db-inventory:
    image: mysql:8
    container_name: inventory-db
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: inventory
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    networks:
      - app-network

networks:
    app-network:
      driver: bridge

